version: '3'
services:
  prismaserverlicence:
    image: prismagraphql/prisma:1.17
    restart: always
    hostname: prismaserverlicence
    ports:
    - "4477:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          licence:
            connector: postgres
            host: dbserver
            port: 5432
            database: GenetixLicence
            user: prisma
            password: prisma
            migrations: true
            # rawAccess: true
#   postgres:
#     image: postgres
#     restart: always
#     environment:
#       POSTGRES_USER: prisma
#       POSTGRES_PASSWORD: prisma
#     volumes:
#       - postgres:/var/lib/postgresql/data
# volumes:
#   postgres:
